---
abstract: 'A humble SMB network protocol implementation in Perl'
author:
  - 'Mikhael Goikhman <migo@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.98, CPAN::Meta::Converter version 2.140640'
license: open_source
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: SMB
no_index:
  directory:
    - t
    - inc
requires:
  Digest::HMAC_MD5: '0'
  Exporter: '0'
  Fcntl: '0'
  File::Basename: '0'
  File::Glob: '0'
  IO::Select: '0'
  IO::Socket: '0'
  POSIX: '0'
  Sys::Hostname: '0'
  Time::HiRes: '0'
  perl: '5.01'
version: '0.04'
